name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  tests:
    services:
      db:
        image: postgres:9.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby: 2.4.5
            gemfile: rails_5_0

          - ruby: 2.4.5
            gemfile: rails_5_1

          - ruby: 2.4.5
            gemfile: rails_5_2

          - ruby: 2.5.3
            gemfile: rails_5_0

          - ruby: 2.6.5
            gemfile: rails_5_2

          - ruby: 2.6.5
            gemfile: rails_6_0

          - ruby: 2.7.0
            gemfile: rails_6_0

          - ruby: 2.7.0
            gemfile: rails_6_1

          - ruby: 2.7.0
            gemfile: rails_edge


    name: ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install dependencies
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}.gemfile"
        sudo apt install -yqq libpq-dev
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rspec
